definitions:
  custom_error.AppError:
    properties:
      error: {}
      httpErrorCode:
        type: integer
      message:
        type: string
    type: object
  models.AuthRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.AuthResponse:
    properties:
      jwt:
        type: string
      refresh:
        type: string
    type: object
host: localhost:9993
info:
  contact: {}
  description: Microservice that is developed for authorization and authentication
    purposes
  title: Auth service
  version: "1.0"
paths:
  /token:
    post:
      consumes:
      - application/json
      description: get token by creds
      parameters:
      - description: auth request body
        in: body
        name: AuthRequest
        required: true
        schema:
          $ref: '#/definitions/models.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/custom_error.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/custom_error.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/custom_error.AppError'
      summary: generates token
      tags:
      - token
swagger: "2.0"
